// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSaoC5vxS8RCg26gHwv-V_9i3j5I_vlD8',
    appId: '1:1050318985848:web:a94d5786b2a409f4cfab8d',
    messagingSenderId: '1050318985848',
    projectId: 'food-court-plus',
    authDomain: 'food-court-plus.firebaseapp.com',
    storageBucket: 'food-court-plus.firebasestorage.app',
    measurementId: 'G-W7X3D69RSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcOl6jgBvLMvostJ2_XQXMSWa8aqzsjO8',
    appId: '1:1050318985848:android:dab051bb4cc45eb8cfab8d',
    messagingSenderId: '1050318985848',
    projectId: 'food-court-plus',
    storageBucket: 'food-court-plus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIjIMe0UkMiLqrmX9LuZH2o5Vxn0OeKeU',
    appId: '1:1050318985848:ios:f231e18e4933dca3cfab8d',
    messagingSenderId: '1050318985848',
    projectId: 'food-court-plus',
    storageBucket: 'food-court-plus.firebasestorage.app',
    iosBundleId: 'com.example.foodcourtplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIjIMe0UkMiLqrmX9LuZH2o5Vxn0OeKeU',
    appId: '1:1050318985848:ios:f231e18e4933dca3cfab8d',
    messagingSenderId: '1050318985848',
    projectId: 'food-court-plus',
    storageBucket: 'food-court-plus.firebasestorage.app',
    iosBundleId: 'com.example.foodcourtplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSaoC5vxS8RCg26gHwv-V_9i3j5I_vlD8',
    appId: '1:1050318985848:web:f453b6c9c663307dcfab8d',
    messagingSenderId: '1050318985848',
    projectId: 'food-court-plus',
    authDomain: 'food-court-plus.firebaseapp.com',
    storageBucket: 'food-court-plus.firebasestorage.app',
    measurementId: 'G-9SP7148X68',
  );
}
